name: "Setup Android modded android.jar"
author: "1fexd & Reginer"
description: "Replace android.jar with Reginer's modded version"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "list"
  color: "green"
